version: alpha-007
runtime: go
api_version: go1

handlers:
  #- url: /.well-known/acme-challenge/XXXX
  #  mime_type: text/plain
  #  static_files: static/letsencrypt/XXXX.txt
  #  upload: static/letsencrypt/XXXX.txt

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: static/public/favicon.ico
  upload: static/public/favicon.ico

- url: /.*
  script: _go_app
  secure: always
